---
- name: Install misc tools
  ansible.builtin.apt:
    name:
      - git
      - tmux
      - curl
      - acl
      - rsync
      - python3-pip
      - whois
      - python3-openssl
      - glances
    update_cache: true
  retries: 3
  delay: 5
  become: true

- name: Hack, disable externally managed python3-pip
  ansible.builtin.file:
    path: /usr/lib/python3.11/EXTERNALLY-MANAGED
    state: absent
  become: true

- name: Install docker python library
  ansible.builtin.pip:
    name:
      - PyYAML==5.3.1
      - docker
      - docker-compose
    state: present
  become: true
