---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true
  become: true

- name: Copy Nginx configuration
  ansible.builtin.template:
    src: "{{ nginx_config }}"
    dest: "/etc/nginx/nginx.conf"
    mode: "0644"
  become: true
  notify: restart nginx
