---
- name: Download Step CA
  ansible.builtin.get_url:
    url: "https://dl.smallstep.com/certificates/docs-ca-install/latest/step-ca_amd64.deb"
    dest: /tmp/step-ca_amd64.deb
    mode: "0644"
  register: step_ca_download

- name: Install step CA
  ansible.builtin.apt:
    deb: /tmp/step-ca_amd64.deb
    state: present
  when: step_ca_download.changed
  become: true

- name: Download Step CLI
  ansible.builtin.get_url:
    url: "https://dl.smallstep.com/cli/docs-ca-install/latest/step-cli_amd64.deb"
    dest: "/tmp/step-cli_amd64.deb"
    mode: "0644"
  register: step_cli_download

- name: Install step CLI
  ansible.builtin.apt:
    deb: /tmp/step-cli_amd64.deb
    state: present
  when: step_cli_download.changed
  become: true

- name: Create CA password file
  ansible.builtin.copy:
    content: "{{ step_ca_password }}"
    dest: /etc/step-ca-password
    mode: "0600"
  become: true

- name: Check if CA is initialized
  ansible.builtin.stat:
    path: "/root/.step/certs/root_ca.crt"
  register: step_ca_initialized
  become: true

- name: Generate CA
  ansible.builtin.command: >
    step-cli ca init --deployment-type=standalone 
    --name=Bakunin --dns=ca.bakunin.local --address=:443 
    --acme --provisioner=me@bakunin.local 
    --password-file=/etc/ca-password
  register: step_ca_init
  become: true
  when: step_ca_initialized.stat.exists == false

- name: Copy systemd unit file
  ansible.builtin.copy:
    src: step-ca.service
    dest: /etc/systemd/system/step-ca.service
    mode: "0644"
  become: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Start step CA
  ansible.builtin.systemd:
    name: step-ca
    state: started
    enabled: true
  become: true

- name: Get CA fingerprint
  ansible.builtin.command: step-cli certificate fingerprint /root/.step/certs/root_ca.crt
  register: step_ca_fingerprint
  become: true

- name: Register CA fingerprint as fact
  ansible.builtin.set_fact:
    step_ca_fingerprint: "{{ step_ca_fingerprint.stdout_lines[0] }}"
